Ta authentication
Valuacion-App/tasacion-app-api pull request #3
Opened 2023-12-28 22:38 UTC by Dragondes

2023-12-30 17:40 UTC, FrozstDev requested changes

2023-12-30 17:40 UTC, FrozstDev commented on src/app.js
Ya no se usa una creacion para crear roles

2023-12-30 17:40 UTC, FrozstDev commented on src/config.js
Elimina el archivo y usa el .env, ademas hay otro archivo .env.example ahi colocas las nuevas variables colocadas, como e s un avariable con infomracion sensible no debe estar visible para nadie

2023-12-30 17:40 UTC, FrozstDev commented on src/controllers/auth.controller.js
Elimina comentarios, cuando pusheas a la develop, debemos intentar tener comentado codigo, que ya no usemos

2023-12-30 17:40 UTC, FrozstDev commented on src/libs/initialSetup.js
Eliminar este archivo

2023-12-30 17:40 UTC, FrozstDev commented on src/models/mongo/role.model.js
Eliminar archivo

2023-12-30 17:40 UTC, FrozstDev commented on src/routes/state.routes.js
El verify token debe estar en todas las rutas, hasta definir cuales seran publicos

2024-01-02 17:51 UTC, JuanJoseQuiroga approved these changes
una vez completadas las observaciones tiene mi approve.

2024-01-02 18:31 UTC, FrozstDev approved these changes

2024-01-02 18:31 UTC, merged